# ProxyMotd - Running At Spigot.
# Developed by InitDev | Version ~ 1.0.0
# [!] Some features of bungee-cord version is not available at this release.
config:
  # Prefix for the messages.
  prefix: "&8[&6ProxyMotd&8]"

  sounds:
    # Allow replay sounds?
    # This sounds can be customized.
    allow: true

    # [!] Can view distint sounds at: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    no-perm: ENTITY_ITEM_BREAK
    reload: UI_BUTTON_CLICK
    maintenance: ENTITY_EXPERIENCE_ORB_PICKUP

    # Volume level (Float).
    volume-level: 1.0

  titles:
    # Allow send titles?
    # This titles can be customized.
    allow: true

    # Titles Time Parameters.
    fade-in: 20
    stay: 60
    fade-out: 20

  motd:
    # Allow use the New Motd System?
    allow: true

    # Allow random lines?
    # Every time what the player update the servers list,
    # will be change the motd lines.
    allow-random-lines: true

    # Add one player more to max players amount every time that some join? Ex: 5/6 => 6/7
    # [!] This bypass the max-players amount set at the config.
    one-player-more: true

    # Motd Types.
    common:
      up:
        - "     &6&lProxyMotd &8| &aCustomizable MOTD for your Server!"
        - "          &6&lProxyMotd &8| &fDeveloped by &eInitDev"
        - "        &6&lProxyMotd &8| &fSupport for &7[1.8 - 1.19]"
      down:
        - "                      &bCustomize the MOTD!"
        - "                    &aInvite to your Friends!"
        - "                   &fAvailable At: &eSpigotMC"
    maintenance:
      up: [ "        &6&lProxyMotd &8| &fSupport for &7[1.8 - 1.19]" ]
      down: [ "              &cWe are under maintenance!" ]

    # Set the players number (max) to zero?
    # This happens if the maintenance mode is enabled.
    # [!] This bypass the players amount set at the config.
    players-to-zero: true

    # Max Players Amount:
    max: 7500

messages:
  # To use the prefix, use the variable: '#prefix'.
  no-perm: "#prefix &cYou don't have permission for that!"
  no-command: "#prefix &cThat command has not been added!"

  help:
    - "&6ProtonMotd (Spigot) &8| &eAvailable Commands."
    - "&7 - &a/protonmotd help &fShows this message."
    - "&7 - &a/protonmotd reload &fReload the config."
    - "&7 - &a/protonmotd maintenance &fToggle the maintenance mode."

  reload: "#prefix &aThe plugin configuration has been reloaded successful!"

  maintenance-on: "#prefix &eMaintenance Mode: &aON"
  maintenance-off: "#prefix &eMaintenance Mode: &cOFF"
  maintenance-title-on: "&6&lMAINTENANCE"
  maintenance-subtitle-on: "&fThe maintenance has been &eactivated&f."
  maintenance-title-off: "&6&lMAINTENANCE"
  maintenance-subtitle-off: "&fThe maintenance has been &edisabled&f."